# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 10.10.10.52
  become: yes

  tasks:

- name: Call Roles
  hosts: 10.10.10.52
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
